# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbbe7c848a12859ee4a5634baa4a53697f14cfd89212c1429c106b9b08a344a6840ec1a631fa919d2361870963da973e6ba853ead4f9d787219cc4baeabc801a

test:
  secret_key_base: 74f8521bae03bc3cebd16d54bca1852608ca4936d66f4932a64871ad9b8929432826d2a4c917cf12d43d2c1037d89441ab4050979883ab422131f18bb7ffb25f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
